django/make-instargram/django_app/member/urls.py
from django.conf.urls import url
from . import views

app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
]

django/make-instargram/django_app/templates/common/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" href="{% static 'css/layout.css' %}">
	<link rel="stylesheet" href="{% static 'css/post.css' %}">
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">
	<title>Instagram</title>
</head>
<body>
	<div id="wrap">
		<header class="top-header">
			<nav>
				<div class="nav-left nav-item">
					<a href="{% url 'post:post_list' %}">
						<img src="{% static 'images/logo.png' %}" alt="">
					</a>
				</div>
				<div class="nav-center nav-item">
					<input type="text" placeholder="Search...">
				</div>
				<div class="nav-right nav-item">
					<a href="#">
						<img src="{% static 'images/icon_explore.png' %}" alt="">
					</a>
					<a href="#">
						<img src="{% static 'images/icon_heart.png' %}" alt="">
					</a>
					<a href="#">
						<img src="{% static 'images/icon_profile.png' %}" alt="">
					</a>
				</div>
			</nav>
			<nav>
				<div>
					{% if user.is_authenticated %}
					<a href="{% url 'post:post_create' %}" class="btn" style="float:left; margin-top: -7px;">사진올리기</a>
					{{ user }} <a href="#" class="btn">로그아웃</a>
					{% else %}
					<a href="{% url 'member:login' %}" class="btn">로그인</a>
					<a href="{% url 'member:signup' %}" class="btn">회원가입</a>
					{% endif %}
				</div>
			</nav>
		</header>

		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</body>
</html>